### ISSUE TITLE
Daily forecast time tracking

### ISSUE THREAD

**Issue by jeffm999** [pkissling/clock-weather-card#107]
**Checklist:**

- [ ] I updated to the latest version available -yes
- [ ] I cleared the cache of my browser -yes
- [ ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there. -yes

**Release with the issue:** 
v1.09

**Last working release (if known):**
v1.0.9
**Browser and Operating System:**
chromium, archlinux, 

**Description of problem:**
Is the black dot on the today's forecast bar meant to be tracking  time?  If it's tracking time, it seems to be tracking UTC time and not local time. What I see at 21:49 local time is bright sunshine which is not as it is right now.

**Javascript errors shown in the web inspector (if applicable):**

```
![image](https://user-images.githubusercontent.com/49336389/200116495-6bf7fc86-2f63-48a0-9bc4-60e84d82f5d3.png)


```

**Additional information:**

**Comment by pkissling** [comment]
hi @jeffm999, the dot does not indicate the time. it indicates the current temperature.
btw did you apply some card-mod modifications? the dot is supposed to be white with a black outline. see the card example in the README.md

**Comment by jeffm999** [comment]
aha. that makes sense now

this is my card config:

type: custom:clock-weather-card
entity: weather.eltham_north
title: Weather Forecast Eltham North
sun_entity: sun.sun
weather_icon_type: fill
animated_icon: true
forecast_days: 7
time_format: 24
hide_today_section: false
hide_forecast_section: false
date_pattern: dd MMMM yyyy
locale: en

rgds

**Comment by pkissling** [comment]
would you also please tell me the browser (and version) you are using? i want to follow up on that black dot

**Comment by jeffm999** [comment]
Chromium Version 107.0.5304.87 (Official Build) Arch Linux (64-bit)

rgds
